apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      volumes:
      - name: otel-agent-volume
        emptyDir: {}
      initContainers:
      - name: otel-agent-attach
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
        command: ["cp", "-r", "/autoinstrumentation/.", "/otel-share/"]
        volumeMounts:
        - name: otel-agent-volume
          mountPath: /otel-share
      containers:
      - name: service-a
        image: asia-east1-docker.pkg.dev/platypus-lab01/otel-repo/simple-febedb-app:10
        command: ["/bin/sh", "-c"]
        args:
          - |
            export PYTHONPATH=$PYTHONPATH:/otel-share;
            export PATH=$PATH:/otel-share/bin;
            /otel-share/bin/opentelemetry-instrument python service_a.py
        env:
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "service-a-frontend"
        volumeMounts:
        - name: otel-agent-volume
          mountPath: /otel-share
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIp
  selector:
    app: service-a
  ports:
  - port: 80
    targetPort: 5001
